"on":
  pull_request:
    types:
    - closed
name: Porter Preview Environment
jobs:
  porter-delete-preview:
    runs-on: ubuntu-latest
    steps:
    - name: Delete Porter preview env
      timeout-minutes: 30
      uses: porter-dev/porter-delete-preview-action@v0.1.0
      with:
        cluster: "59"
        host: https://dashboard.staging.getporter.dev
        installation_id: "18462798"
        namespace: pr-${{ github.event.pull_request.number }}-python-getting-started
        project: "12"
        repo_name: python-getting-started
        repo_owner: ${{ github.repository_owner }}
        token: ${{ secrets.PORTER_TOKEN_12 }}
